apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
commonLabels:
  env: staging
images:
- name: react-app
  newName: react-app
  newTag: staging

configMapGenerator:
- name: react-app-config
  envs:
  - frontend.env