apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
commonLabels:
  env: development
images:
- name: react-app
  newName: react-app
  newTag: dev

configMapGenerator:
- name: react-app-config
  envs:
  - frontend.env